version: "3.8"
services:
  api:
    image: egorgo/go-infra-backend:0.0.10
    platform: linux/amd64
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - shared-network
  ui:
    image: egorgo/go-infra-front:0.0.1
    platform: linux/amd64
    ports:
      - 5002:${UI_PORT}
    networks:
      - shared-network
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - shared-network
  nginx:
    build: ./nginx
    platform: linux/amd64
    ports:
      - 80:${NGINX_PORT}
    depends_on:
      - ui
      - api
    networks:
      - shared-network

networks:
  shared-network: