version: "3.8"
services:
  api:
    image: egorgo/go-infra-backend:0.0.1
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - shared-network
    expose:
      - ${API_PORT}
  ui:
    image: egorgo/go-infra-front:0.0.1
    networks:
      - shared-network
    ports:
      - ${UI_PORT}:80
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - shared-network
  nginx:
    build: ./nginx
    ports:
      - 80:${NGINX_PORT}
    depends_on:
      - api
      - ui
    networks:
      - shared-network

networks:
  shared-network: